apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-argocd-app
spec:
  selector:
    matchLabels:
      app: spring-argocd-app
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-argocd-app
    spec:
      containers:
        - name: spring-argocd-app
          image: viju2008/my-app-image:main-b30e3b68ff1df05ab5b88620cceb0567e17f7d25
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: username
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
