apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-argocd-app
spec:
  selector:
    matchLabels:
      app: spring-argocd-app
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-argocd-app
    spec:
      containers:
        - name: spring-argocd-app
          image: viju2008/my-app-image:main-610534ca588a90c884253cab5b3e00f71a2cc94c
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
